/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * LovingApplicationApi - axios parameter creator
 * @export
 */
export const LovingApplicationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sayHello: async (name?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/sayHello`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LovingApplicationApi - functional programming interface
 * @export
 */
export const LovingApplicationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LovingApplicationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sayHello(name?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sayHello(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LovingApplicationApi.sayHello']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LovingApplicationApi - factory interface
 * @export
 */
export const LovingApplicationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LovingApplicationApiFp(configuration)
    return {
        /**
         * 
         * @param {LovingApplicationApiSayHelloRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sayHello(requestParameters: LovingApplicationApiSayHelloRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.sayHello(requestParameters.name, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LovingApplicationApi - interface
 * @export
 * @interface LovingApplicationApi
 */
export interface LovingApplicationApiInterface {
    /**
     * 
     * @param {LovingApplicationApiSayHelloRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LovingApplicationApiInterface
     */
    sayHello(requestParameters?: LovingApplicationApiSayHelloRequest, options?: RawAxiosRequestConfig): AxiosPromise<string>;

}

/**
 * Request parameters for sayHello operation in LovingApplicationApi.
 * @export
 * @interface LovingApplicationApiSayHelloRequest
 */
export interface LovingApplicationApiSayHelloRequest {
    /**
     * 
     * @type {string}
     * @memberof LovingApplicationApiSayHello
     */
    readonly name?: string
}

/**
 * LovingApplicationApi - object-oriented interface
 * @export
 * @class LovingApplicationApi
 * @extends {BaseAPI}
 */
export class LovingApplicationApi extends BaseAPI implements LovingApplicationApiInterface {
    /**
     * 
     * @param {LovingApplicationApiSayHelloRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LovingApplicationApi
     */
    public sayHello(requestParameters: LovingApplicationApiSayHelloRequest = {}, options?: RawAxiosRequestConfig) {
        return LovingApplicationApiFp(this.configuration).sayHello(requestParameters.name, options).then((request) => request(this.axios, this.basePath));
    }
}

