/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { RitualRecommendationCreateRequest } from '../models';
// @ts-ignore
import type { RitualRecommendationDTO } from '../models';
// @ts-ignore
import type { RitualRecommendationUpdateRequest } from '../models';
/**
 * RitualRecommendationControllerApi - axios parameter creator
 * @export
 */
export const RitualRecommendationControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} userId 
         * @param {RitualRecommendationCreateRequest} ritualRecommendationCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create: async (userId: string, ritualRecommendationCreateRequest: RitualRecommendationCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('create', 'userId', userId)
            // verify required parameter 'ritualRecommendationCreateRequest' is not null or undefined
            assertParamExists('create', 'ritualRecommendationCreateRequest', ritualRecommendationCreateRequest)
            const localVarPath = `/api/ritual-recommendation`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ritualRecommendationCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAll: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('listAll', 'userId', userId)
            const localVarPath = `/api/ritual-recommendation`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} userId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listById: async (userId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('listById', 'userId', userId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listById', 'id', id)
            const localVarPath = `/api/ritual-recommendation/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} userId 
         * @param {string} id 
         * @param {RitualRecommendationUpdateRequest} ritualRecommendationUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRecommendationAndRitualHistoryStatus: async (userId: string, id: string, ritualRecommendationUpdateRequest: RitualRecommendationUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('updateRecommendationAndRitualHistoryStatus', 'userId', userId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateRecommendationAndRitualHistoryStatus', 'id', id)
            // verify required parameter 'ritualRecommendationUpdateRequest' is not null or undefined
            assertParamExists('updateRecommendationAndRitualHistoryStatus', 'ritualRecommendationUpdateRequest', ritualRecommendationUpdateRequest)
            const localVarPath = `/api/ritual-recommendation/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ritualRecommendationUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RitualRecommendationControllerApi - functional programming interface
 * @export
 */
export const RitualRecommendationControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RitualRecommendationControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} userId 
         * @param {RitualRecommendationCreateRequest} ritualRecommendationCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(userId: string, ritualRecommendationCreateRequest: RitualRecommendationCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RitualRecommendationDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create(userId, ritualRecommendationCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RitualRecommendationControllerApi.create']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAll(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RitualRecommendationDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listAll(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RitualRecommendationControllerApi.listAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} userId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listById(userId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RitualRecommendationDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listById(userId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RitualRecommendationControllerApi.listById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} userId 
         * @param {string} id 
         * @param {RitualRecommendationUpdateRequest} ritualRecommendationUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateRecommendationAndRitualHistoryStatus(userId: string, id: string, ritualRecommendationUpdateRequest: RitualRecommendationUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateRecommendationAndRitualHistoryStatus(userId, id, ritualRecommendationUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RitualRecommendationControllerApi.updateRecommendationAndRitualHistoryStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RitualRecommendationControllerApi - factory interface
 * @export
 */
export const RitualRecommendationControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RitualRecommendationControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {RitualRecommendationControllerApiCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(requestParameters: RitualRecommendationControllerApiCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<RitualRecommendationDTO> {
            return localVarFp.create(requestParameters.userId, requestParameters.ritualRecommendationCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RitualRecommendationControllerApiListAllRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAll(requestParameters: RitualRecommendationControllerApiListAllRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<RitualRecommendationDTO>> {
            return localVarFp.listAll(requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RitualRecommendationControllerApiListByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listById(requestParameters: RitualRecommendationControllerApiListByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<RitualRecommendationDTO> {
            return localVarFp.listById(requestParameters.userId, requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RitualRecommendationControllerApiUpdateRecommendationAndRitualHistoryStatusRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRecommendationAndRitualHistoryStatus(requestParameters: RitualRecommendationControllerApiUpdateRecommendationAndRitualHistoryStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateRecommendationAndRitualHistoryStatus(requestParameters.userId, requestParameters.id, requestParameters.ritualRecommendationUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RitualRecommendationControllerApi - interface
 * @export
 * @interface RitualRecommendationControllerApi
 */
export interface RitualRecommendationControllerApiInterface {
    /**
     * 
     * @param {RitualRecommendationControllerApiCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RitualRecommendationControllerApiInterface
     */
    create(requestParameters: RitualRecommendationControllerApiCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<RitualRecommendationDTO>;

    /**
     * 
     * @param {RitualRecommendationControllerApiListAllRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RitualRecommendationControllerApiInterface
     */
    listAll(requestParameters: RitualRecommendationControllerApiListAllRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<RitualRecommendationDTO>>;

    /**
     * 
     * @param {RitualRecommendationControllerApiListByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RitualRecommendationControllerApiInterface
     */
    listById(requestParameters: RitualRecommendationControllerApiListByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<RitualRecommendationDTO>;

    /**
     * 
     * @param {RitualRecommendationControllerApiUpdateRecommendationAndRitualHistoryStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RitualRecommendationControllerApiInterface
     */
    updateRecommendationAndRitualHistoryStatus(requestParameters: RitualRecommendationControllerApiUpdateRecommendationAndRitualHistoryStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * Request parameters for create operation in RitualRecommendationControllerApi.
 * @export
 * @interface RitualRecommendationControllerApiCreateRequest
 */
export interface RitualRecommendationControllerApiCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof RitualRecommendationControllerApiCreate
     */
    readonly userId: string

    /**
     * 
     * @type {RitualRecommendationCreateRequest}
     * @memberof RitualRecommendationControllerApiCreate
     */
    readonly ritualRecommendationCreateRequest: RitualRecommendationCreateRequest
}

/**
 * Request parameters for listAll operation in RitualRecommendationControllerApi.
 * @export
 * @interface RitualRecommendationControllerApiListAllRequest
 */
export interface RitualRecommendationControllerApiListAllRequest {
    /**
     * 
     * @type {string}
     * @memberof RitualRecommendationControllerApiListAll
     */
    readonly userId: string
}

/**
 * Request parameters for listById operation in RitualRecommendationControllerApi.
 * @export
 * @interface RitualRecommendationControllerApiListByIdRequest
 */
export interface RitualRecommendationControllerApiListByIdRequest {
    /**
     * 
     * @type {string}
     * @memberof RitualRecommendationControllerApiListById
     */
    readonly userId: string

    /**
     * 
     * @type {string}
     * @memberof RitualRecommendationControllerApiListById
     */
    readonly id: string
}

/**
 * Request parameters for updateRecommendationAndRitualHistoryStatus operation in RitualRecommendationControllerApi.
 * @export
 * @interface RitualRecommendationControllerApiUpdateRecommendationAndRitualHistoryStatusRequest
 */
export interface RitualRecommendationControllerApiUpdateRecommendationAndRitualHistoryStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof RitualRecommendationControllerApiUpdateRecommendationAndRitualHistoryStatus
     */
    readonly userId: string

    /**
     * 
     * @type {string}
     * @memberof RitualRecommendationControllerApiUpdateRecommendationAndRitualHistoryStatus
     */
    readonly id: string

    /**
     * 
     * @type {RitualRecommendationUpdateRequest}
     * @memberof RitualRecommendationControllerApiUpdateRecommendationAndRitualHistoryStatus
     */
    readonly ritualRecommendationUpdateRequest: RitualRecommendationUpdateRequest
}

/**
 * RitualRecommendationControllerApi - object-oriented interface
 * @export
 * @class RitualRecommendationControllerApi
 * @extends {BaseAPI}
 */
export class RitualRecommendationControllerApi extends BaseAPI implements RitualRecommendationControllerApiInterface {
    /**
     * 
     * @param {RitualRecommendationControllerApiCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RitualRecommendationControllerApi
     */
    public create(requestParameters: RitualRecommendationControllerApiCreateRequest, options?: RawAxiosRequestConfig) {
        return RitualRecommendationControllerApiFp(this.configuration).create(requestParameters.userId, requestParameters.ritualRecommendationCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RitualRecommendationControllerApiListAllRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RitualRecommendationControllerApi
     */
    public listAll(requestParameters: RitualRecommendationControllerApiListAllRequest, options?: RawAxiosRequestConfig) {
        return RitualRecommendationControllerApiFp(this.configuration).listAll(requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RitualRecommendationControllerApiListByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RitualRecommendationControllerApi
     */
    public listById(requestParameters: RitualRecommendationControllerApiListByIdRequest, options?: RawAxiosRequestConfig) {
        return RitualRecommendationControllerApiFp(this.configuration).listById(requestParameters.userId, requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RitualRecommendationControllerApiUpdateRecommendationAndRitualHistoryStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RitualRecommendationControllerApi
     */
    public updateRecommendationAndRitualHistoryStatus(requestParameters: RitualRecommendationControllerApiUpdateRecommendationAndRitualHistoryStatusRequest, options?: RawAxiosRequestConfig) {
        return RitualRecommendationControllerApiFp(this.configuration).updateRecommendationAndRitualHistoryStatus(requestParameters.userId, requestParameters.id, requestParameters.ritualRecommendationUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

