/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { RitualRecommendationDTO } from '../models';
// @ts-ignore
import type { RitualRecommendationUpdateStatusRequest } from '../models';
/**
 * RitualRecommendationControllerApi - axios parameter creator
 * @export
 */
export const RitualRecommendationControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ritual-recommendation`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listById', 'id', id)
            const localVarPath = `/api/ritual-recommendation/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {RitualRecommendationUpdateStatusRequest} ritualRecommendationUpdateStatusRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStatus: async (id: string, ritualRecommendationUpdateStatusRequest: RitualRecommendationUpdateStatusRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateStatus', 'id', id)
            // verify required parameter 'ritualRecommendationUpdateStatusRequest' is not null or undefined
            assertParamExists('updateStatus', 'ritualRecommendationUpdateStatusRequest', ritualRecommendationUpdateStatusRequest)
            const localVarPath = `/api/ritual-recommendation/{id}/status`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ritualRecommendationUpdateStatusRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RitualRecommendationControllerApi - functional programming interface
 * @export
 */
export const RitualRecommendationControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RitualRecommendationControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RitualRecommendationDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RitualRecommendationControllerApi.listAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RitualRecommendationDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RitualRecommendationControllerApi.listById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {RitualRecommendationUpdateStatusRequest} ritualRecommendationUpdateStatusRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateStatus(id: string, ritualRecommendationUpdateStatusRequest: RitualRecommendationUpdateStatusRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RitualRecommendationDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateStatus(id, ritualRecommendationUpdateStatusRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RitualRecommendationControllerApi.updateStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RitualRecommendationControllerApi - factory interface
 * @export
 */
export const RitualRecommendationControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RitualRecommendationControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<RitualRecommendationDTO>> {
            return localVarFp.listAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RitualRecommendationControllerApiListByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listById(requestParameters: RitualRecommendationControllerApiListByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<RitualRecommendationDTO> {
            return localVarFp.listById(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RitualRecommendationControllerApiUpdateStatusRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStatus(requestParameters: RitualRecommendationControllerApiUpdateStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<RitualRecommendationDTO> {
            return localVarFp.updateStatus(requestParameters.id, requestParameters.ritualRecommendationUpdateStatusRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RitualRecommendationControllerApi - interface
 * @export
 * @interface RitualRecommendationControllerApi
 */
export interface RitualRecommendationControllerApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RitualRecommendationControllerApiInterface
     */
    listAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<RitualRecommendationDTO>>;

    /**
     * 
     * @param {RitualRecommendationControllerApiListByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RitualRecommendationControllerApiInterface
     */
    listById(requestParameters: RitualRecommendationControllerApiListByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<RitualRecommendationDTO>;

    /**
     * 
     * @param {RitualRecommendationControllerApiUpdateStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RitualRecommendationControllerApiInterface
     */
    updateStatus(requestParameters: RitualRecommendationControllerApiUpdateStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<RitualRecommendationDTO>;

}

/**
 * Request parameters for listById operation in RitualRecommendationControllerApi.
 * @export
 * @interface RitualRecommendationControllerApiListByIdRequest
 */
export interface RitualRecommendationControllerApiListByIdRequest {
    /**
     * 
     * @type {string}
     * @memberof RitualRecommendationControllerApiListById
     */
    readonly id: string
}

/**
 * Request parameters for updateStatus operation in RitualRecommendationControllerApi.
 * @export
 * @interface RitualRecommendationControllerApiUpdateStatusRequest
 */
export interface RitualRecommendationControllerApiUpdateStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof RitualRecommendationControllerApiUpdateStatus
     */
    readonly id: string

    /**
     * 
     * @type {RitualRecommendationUpdateStatusRequest}
     * @memberof RitualRecommendationControllerApiUpdateStatus
     */
    readonly ritualRecommendationUpdateStatusRequest: RitualRecommendationUpdateStatusRequest
}

/**
 * RitualRecommendationControllerApi - object-oriented interface
 * @export
 * @class RitualRecommendationControllerApi
 * @extends {BaseAPI}
 */
export class RitualRecommendationControllerApi extends BaseAPI implements RitualRecommendationControllerApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RitualRecommendationControllerApi
     */
    public listAll(options?: RawAxiosRequestConfig) {
        return RitualRecommendationControllerApiFp(this.configuration).listAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RitualRecommendationControllerApiListByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RitualRecommendationControllerApi
     */
    public listById(requestParameters: RitualRecommendationControllerApiListByIdRequest, options?: RawAxiosRequestConfig) {
        return RitualRecommendationControllerApiFp(this.configuration).listById(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RitualRecommendationControllerApiUpdateStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RitualRecommendationControllerApi
     */
    public updateStatus(requestParameters: RitualRecommendationControllerApiUpdateStatusRequest, options?: RawAxiosRequestConfig) {
        return RitualRecommendationControllerApiFp(this.configuration).updateStatus(requestParameters.id, requestParameters.ritualRecommendationUpdateStatusRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

