/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { UserContextDTO } from '../models';
/**
 * UserContextControllerApi - axios parameter creator
 * @export
 */
export const UserContextControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {UserContextDTO} userContextDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUserContext: async (userContextDTO: UserContextDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userContextDTO' is not null or undefined
            assertParamExists('createUserContext', 'userContextDTO', userContextDTO)
            const localVarPath = `/api/user-contexts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userContextDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserContexts: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/user-contexts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserContextControllerApi - functional programming interface
 * @export
 */
export const UserContextControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserContextControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {UserContextDTO} userContextDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUserContext(userContextDTO: UserContextDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserContextDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createUserContext(userContextDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserContextControllerApi.createUserContext']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserContexts(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserContextDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserContexts(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserContextControllerApi.getUserContexts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserContextControllerApi - factory interface
 * @export
 */
export const UserContextControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserContextControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {UserContextControllerApiCreateUserContextRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUserContext(requestParameters: UserContextControllerApiCreateUserContextRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserContextDTO> {
            return localVarFp.createUserContext(requestParameters.userContextDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserContexts(options?: RawAxiosRequestConfig): AxiosPromise<Array<UserContextDTO>> {
            return localVarFp.getUserContexts(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserContextControllerApi - interface
 * @export
 * @interface UserContextControllerApi
 */
export interface UserContextControllerApiInterface {
    /**
     * 
     * @param {UserContextControllerApiCreateUserContextRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserContextControllerApiInterface
     */
    createUserContext(requestParameters: UserContextControllerApiCreateUserContextRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserContextDTO>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserContextControllerApiInterface
     */
    getUserContexts(options?: RawAxiosRequestConfig): AxiosPromise<Array<UserContextDTO>>;

}

/**
 * Request parameters for createUserContext operation in UserContextControllerApi.
 * @export
 * @interface UserContextControllerApiCreateUserContextRequest
 */
export interface UserContextControllerApiCreateUserContextRequest {
    /**
     * 
     * @type {UserContextDTO}
     * @memberof UserContextControllerApiCreateUserContext
     */
    readonly userContextDTO: UserContextDTO
}

/**
 * UserContextControllerApi - object-oriented interface
 * @export
 * @class UserContextControllerApi
 * @extends {BaseAPI}
 */
export class UserContextControllerApi extends BaseAPI implements UserContextControllerApiInterface {
    /**
     * 
     * @param {UserContextControllerApiCreateUserContextRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserContextControllerApi
     */
    public createUserContext(requestParameters: UserContextControllerApiCreateUserContextRequest, options?: RawAxiosRequestConfig) {
        return UserContextControllerApiFp(this.configuration).createUserContext(requestParameters.userContextDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserContextControllerApi
     */
    public getUserContexts(options?: RawAxiosRequestConfig) {
        return UserContextControllerApiFp(this.configuration).getUserContexts(options).then((request) => request(this.axios, this.basePath));
    }
}

