/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChatMessageDTO } from './chat-message-dto';

/**
 * 
 * @export
 * @interface ChatSessionDTO
 */
export interface ChatSessionDTO {
    /**
     * 
     * @type {string}
     * @memberof ChatSessionDTO
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ChatSessionDTO
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatSessionDTO
     */
    'lastMessagePreview'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatSessionDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatSessionDTO
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {Array<ChatMessageDTO>}
     * @memberof ChatSessionDTO
     */
    'messages'?: Array<ChatMessageDTO>;
}

