/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserRitualDTO } from './user-ritual-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { UserRitualPackDTO } from './user-ritual-pack-dto';

/**
 * 
 * @export
 * @interface CurrentRitualsDTO
 */
export interface CurrentRitualsDTO {
    /**
     * 
     * @type {Array<UserRitualPackDTO>}
     * @memberof CurrentRitualsDTO
     */
    'ritualPacks'?: Array<UserRitualPackDTO>;
    /**
     * 
     * @type {Array<UserRitualDTO>}
     * @memberof CurrentRitualsDTO
     */
    'individualRituals'?: Array<UserRitualDTO>;
}

