/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InfoBullet } from './info-bullet';

/**
 * 
 * @export
 * @interface InfoSection
 */
export interface InfoSection {
    /**
     * 
     * @type {number}
     * @memberof InfoSection
     */
    'order': number;
    /**
     * 
     * @type {string}
     * @memberof InfoSection
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof InfoSection
     */
    'summary': string;
    /**
     * 
     * @type {Array<InfoBullet>}
     * @memberof InfoSection
     */
    'bullets'?: Array<InfoBullet>;
}

