/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const Journey = {
    FeelingDistant: 'FEELING_DISTANT',
    LoveFeelsFlat: 'LOVE_FEELS_FLAT',
    LostTouch: 'LOST_TOUCH',
    CarryingTooMuch: 'CARRYING_TOO_MUCH',
    WeatheringAStorm: 'WEATHERING_A_STORM',
    BridgingTheDivide: 'BRIDGING_THE_DIVIDE',
    LearningToHearEachOther: 'LEARNING_TO_HEAR_EACH_OTHER',
    MakingSpaceForUs: 'MAKING_SPACE_FOR_US',
    KeepTheLoveAlive: 'KEEP_THE_LOVE_ALIVE',
    GrowAndEvolveTogether: 'GROW_AND_EVOLVE_TOGETHER',
    ReturnToSelf: 'RETURN_TO_SELF',
    CelebrateUs: 'CELEBRATE_US'
} as const;

export type Journey = typeof Journey[keyof typeof Journey];



