/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const LifeContext = {
    MorningRoutine: 'Morning Routine',
    EveningRoutine: 'Evening Routine',
    Weekend: 'Weekend',
    Holiday: 'Holiday',
    Anniversary: 'Anniversary',
    DateNight: 'Date Night',
    LongDistance: 'Long Distance',
    StressfulPeriod: 'Stressful Period',
    NewRelationship: 'New Relationship',
    LongTermRelationship: 'Long-term Relationship'
} as const;

export type LifeContext = typeof LifeContext[keyof typeof LifeContext];



