/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SessionSummaryDTO } from './session-summary-dto';

/**
 * 
 * @export
 * @interface ListSessionsResponse
 */
export interface ListSessionsResponse {
    /**
     * 
     * @type {Array<SessionSummaryDTO>}
     * @memberof ListSessionsResponse
     */
    'sessions'?: Array<SessionSummaryDTO>;
    /**
     * 
     * @type {number}
     * @memberof ListSessionsResponse
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof ListSessionsResponse
     */
    'size'?: number;
    /**
     * 
     * @type {number}
     * @memberof ListSessionsResponse
     */
    'totalElements'?: number;
    /**
     * 
     * @type {number}
     * @memberof ListSessionsResponse
     */
    'totalPages'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ListSessionsResponse
     */
    'first'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ListSessionsResponse
     */
    'last'?: boolean;
}

