/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    'access_token'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    'refresh_token'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    'token_type'?: string;
    /**
     * 
     * @type {number}
     * @memberof LoginResponse
     */
    'expires_in'?: number;
}

