/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InfoSection } from './info-section';
// May contain unused imports in some cases
// @ts-ignore
import type { LoveType } from './love-type';

/**
 * 
 * @export
 * @interface LoveTypeInfo
 */
export interface LoveTypeInfo {
    /**
     * 
     * @type {number}
     * @memberof LoveTypeInfo
     */
    'id': number;
    /**
     * 
     * @type {LoveType}
     * @memberof LoveTypeInfo
     */
    'loveType': LoveType;
    /**
     * 
     * @type {string}
     * @memberof LoveTypeInfo
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof LoveTypeInfo
     */
    'subtitle'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoveTypeInfo
     */
    'description'?: string;
    /**
     * 
     * @type {Array<InfoSection>}
     * @memberof LoveTypeInfo
     */
    'sections'?: Array<InfoSection>;
    /**
     * 
     * @type {string}
     * @memberof LoveTypeInfo
     */
    'contentHash'?: string;
}



