/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InfoSection } from './info-section';

/**
 * 
 * @export
 * @interface LoveTypeInfo
 */
export interface LoveTypeInfo {
    /**
     * 
     * @type {number}
     * @memberof LoveTypeInfo
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof LoveTypeInfo
     */
    'loveType'?: LoveTypeInfoLoveTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof LoveTypeInfo
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoveTypeInfo
     */
    'subtitle'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoveTypeInfo
     */
    'description'?: string;
    /**
     * 
     * @type {Array<InfoSection>}
     * @memberof LoveTypeInfo
     */
    'sections'?: Array<InfoSection>;
}

export const LoveTypeInfoLoveTypeEnum = {
    Belong: 'BELONG',
    Fire: 'FIRE',
    Spark: 'SPARK',
    Care: 'CARE',
    Self: 'SELF',
    Build: 'BUILD',
    Grow: 'GROW',
    Beyond: 'BEYOND',
    Grace: 'GRACE'
} as const;

export type LoveTypeInfoLoveTypeEnum = typeof LoveTypeInfoLoveTypeEnum[keyof typeof LoveTypeInfoLoveTypeEnum];


