/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const LoveType = {
    Belong: 'BELONG',
    Fire: 'FIRE',
    Spark: 'SPARK',
    Care: 'CARE',
    Self: 'SELF',
    Build: 'BUILD',
    Grow: 'GROW',
    Beyond: 'BEYOND',
    Grace: 'GRACE'
} as const;

export type LoveType = typeof LoveType[keyof typeof LoveType];



