/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const RelationshipStatus = {
    New: 'NEW',
    Established: 'ESTABLISHED',
    Committed: 'COMMITTED',
    Engaged: 'ENGAGED',
    Married: 'MARRIED',
    Rekindling: 'REKINDLING',
    LongDistance: 'LONG_DISTANCE',
    Casual: 'CASUAL',
    Exploring: 'EXPLORING',
    Other: 'OTHER'
} as const;

export type RelationshipStatus = typeof RelationshipStatus[keyof typeof RelationshipStatus];



