/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RecommendationSource } from './recommendation-source';
// May contain unused imports in some cases
// @ts-ignore
import type { RecommendationStatus } from './recommendation-status';

/**
 * 
 * @export
 * @interface RitualRecommendationDTO
 */
export interface RitualRecommendationDTO {
    /**
     * 
     * @type {string}
     * @memberof RitualRecommendationDTO
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof RitualRecommendationDTO
     */
    'userId': string;
    /**
     * 
     * @type {RecommendationSource}
     * @memberof RitualRecommendationDTO
     */
    'source': RecommendationSource;
    /**
     * 
     * @type {string}
     * @memberof RitualRecommendationDTO
     */
    'sourceId': string;
    /**
     * 
     * @type {string}
     * @memberof RitualRecommendationDTO
     */
    'ritualPackId': string;
    /**
     * 
     * @type {RecommendationStatus}
     * @memberof RitualRecommendationDTO
     */
    'status': RecommendationStatus;
    /**
     * 
     * @type {string}
     * @memberof RitualRecommendationDTO
     */
    'createdAt'?: string;
}



