/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RitualPackDTO
 */
export interface RitualPackDTO {
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'shortDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'fullDescription'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualPackDTO
     */
    'ritualIds'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualPackDTO
     */
    'ritualTypes'?: Array<RitualPackDTORitualTypesEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualPackDTO
     */
    'ritualTones'?: Array<RitualPackDTORitualTonesEnum>;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'sensitivityLevel'?: RitualPackDTOSensitivityLevelEnum;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'effortLevel'?: RitualPackDTOEffortLevelEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualPackDTO
     */
    'loveTypesSupported'?: Array<RitualPackDTOLoveTypesSupportedEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualPackDTO
     */
    'emotionalStatesSupported'?: Array<RitualPackDTOEmotionalStatesSupportedEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualPackDTO
     */
    'relationalNeedsServed'?: Array<RitualPackDTORelationalNeedsServedEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualPackDTO
     */
    'lifeContextsRelevant'?: Array<RitualPackDTOLifeContextsRelevantEnum>;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'semanticSummary'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'status'?: RitualPackDTOStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'createdBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'updatedAt'?: string;
}

export const RitualPackDTORitualTypesEnum = {
    Reflection: 'Reflection',
    Conversation: 'Conversation',
    Play: 'Play',
    Appreciation: 'Appreciation',
    Gratitude: 'Gratitude',
    PhysicalConnection: 'Physical Connection',
    QualityTime: 'Quality Time',
    Adventure: 'Adventure',
    Relaxation: 'Relaxation',
    SelfImprovement: 'Self-Improvement'
} as const;

export type RitualPackDTORitualTypesEnum = typeof RitualPackDTORitualTypesEnum[keyof typeof RitualPackDTORitualTypesEnum];
export const RitualPackDTORitualTonesEnum = {
    Romantic: 'Romantic',
    Playful: 'Playful',
    Serious: 'Serious',
    Lighthearted: 'Lighthearted',
    Intimate: 'Intimate',
    Adventurous: 'Adventurous',
    Calm: 'Calm',
    Energetic: 'Energetic',
    Thoughtful: 'Thoughtful',
    Spontaneous: 'Spontaneous'
} as const;

export type RitualPackDTORitualTonesEnum = typeof RitualPackDTORitualTonesEnum[keyof typeof RitualPackDTORitualTonesEnum];
export const RitualPackDTOSensitivityLevelEnum = {
    Low: 'LOW',
    Moderate: 'MODERATE',
    High: 'HIGH'
} as const;

export type RitualPackDTOSensitivityLevelEnum = typeof RitualPackDTOSensitivityLevelEnum[keyof typeof RitualPackDTOSensitivityLevelEnum];
export const RitualPackDTOEffortLevelEnum = {
    Low: 'LOW',
    Moderate: 'MODERATE',
    High: 'HIGH'
} as const;

export type RitualPackDTOEffortLevelEnum = typeof RitualPackDTOEffortLevelEnum[keyof typeof RitualPackDTOEffortLevelEnum];
export const RitualPackDTOLoveTypesSupportedEnum = {
    Belong: 'BELONG',
    Fire: 'FIRE',
    Spark: 'SPARK',
    Care: 'CARE',
    Self: 'SELF',
    Build: 'BUILD',
    Grow: 'GROW',
    Beyond: 'BEYOND',
    Grace: 'GRACE'
} as const;

export type RitualPackDTOLoveTypesSupportedEnum = typeof RitualPackDTOLoveTypesSupportedEnum[keyof typeof RitualPackDTOLoveTypesSupportedEnum];
export const RitualPackDTOEmotionalStatesSupportedEnum = {
    Happy: 'Happy',
    Sad: 'Sad',
    Anxious: 'Anxious',
    Peaceful: 'Peaceful',
    Excited: 'Excited',
    Tired: 'Tired',
    Stressed: 'Stressed',
    Loving: 'Loving',
    Grateful: 'Grateful',
    Frustrated: 'Frustrated',
    Overwhelmed: 'Overwhelmed'
} as const;

export type RitualPackDTOEmotionalStatesSupportedEnum = typeof RitualPackDTOEmotionalStatesSupportedEnum[keyof typeof RitualPackDTOEmotionalStatesSupportedEnum];
export const RitualPackDTORelationalNeedsServedEnum = {
    Connection: 'Connection',
    Appreciation: 'Appreciation',
    Respect: 'Respect',
    Trust: 'Trust',
    Intimacy: 'Intimacy',
    Support: 'Support',
    Acceptance: 'Acceptance',
    Space: 'Space',
    Security: 'Security',
    Adventure: 'Adventure'
} as const;

export type RitualPackDTORelationalNeedsServedEnum = typeof RitualPackDTORelationalNeedsServedEnum[keyof typeof RitualPackDTORelationalNeedsServedEnum];
export const RitualPackDTOLifeContextsRelevantEnum = {
    MorningRoutine: 'Morning Routine',
    EveningRoutine: 'Evening Routine',
    Weekend: 'Weekend',
    Holiday: 'Holiday',
    Anniversary: 'Anniversary',
    DateNight: 'Date Night',
    LongDistance: 'Long Distance',
    StressfulPeriod: 'Stressful Period',
    NewRelationship: 'New Relationship',
    LongTermRelationship: 'Long-term Relationship'
} as const;

export type RitualPackDTOLifeContextsRelevantEnum = typeof RitualPackDTOLifeContextsRelevantEnum[keyof typeof RitualPackDTOLifeContextsRelevantEnum];
export const RitualPackDTOStatusEnum = {
    Published: 'PUBLISHED',
    Draft: 'DRAFT',
    Archived: 'ARCHIVED'
} as const;

export type RitualPackDTOStatusEnum = typeof RitualPackDTOStatusEnum[keyof typeof RitualPackDTOStatusEnum];


