/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RitualTag } from './ritual-tag';

/**
 * 
 * @export
 * @interface RitualTags
 */
export interface RitualTags {
    /**
     * 
     * @type {RitualTag}
     * @memberof RitualTags
     */
    'loveTypes': RitualTag;
    /**
     * 
     * @type {RitualTag}
     * @memberof RitualTags
     */
    'ritualModes': RitualTag;
    /**
     * 
     * @type {RitualTag}
     * @memberof RitualTags
     */
    'timeTaken': RitualTag;
    /**
     * 
     * @type {RitualTag}
     * @memberof RitualTags
     */
    'relationalNeeds': RitualTag;
    /**
     * 
     * @type {RitualTag}
     * @memberof RitualTags
     */
    'ritualTones': RitualTag;
}

