/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const RitualTone = {
    Warm: 'WARM',
    Playful: 'PLAYFUL',
    Intimate: 'INTIMATE',
    Reflective: 'REFLECTIVE',
    Calm: 'CALM',
    Adventurous: 'ADVENTUROUS',
    Energetic: 'ENERGETIC',
    Healing: 'HEALING',
    Sacred: 'SACRED'
} as const;

export type RitualTone = typeof RitualTone[keyof typeof RitualTone];



