/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MediaAsset } from './media-asset';
// May contain unused imports in some cases
// @ts-ignore
import type { RitualStep } from './ritual-step';

/**
 * 
 * @export
 * @interface RitualDTO
 */
export interface RitualDTO {
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'shortDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'fullDescription'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualDTO
     */
    'ritualTypes'?: Array<RitualDTORitualTypesEnum>;
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'ritualMode'?: RitualDTORitualModeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualDTO
     */
    'ritualTones'?: Array<RitualDTORitualTonesEnum>;
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'sensitivityLevel'?: RitualDTOSensitivityLevelEnum;
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'effortLevel'?: RitualDTOEffortLevelEnum;
    /**
     * 
     * @type {number}
     * @memberof RitualDTO
     */
    'estimatedDurationMinutes'?: number;
    /**
     * 
     * @type {Array<RitualStep>}
     * @memberof RitualDTO
     */
    'ritualSteps'?: Array<RitualStep>;
    /**
     * 
     * @type {Array<MediaAsset>}
     * @memberof RitualDTO
     */
    'mediaAssets'?: Array<MediaAsset>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualDTO
     */
    'loveTypesSupported'?: Array<RitualDTOLoveTypesSupportedEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualDTO
     */
    'emotionalStatesSupported'?: Array<RitualDTOEmotionalStatesSupportedEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualDTO
     */
    'relationalNeedsServed'?: Array<RitualDTORelationalNeedsServedEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualDTO
     */
    'lifeContextsRelevant'?: Array<RitualDTOLifeContextsRelevantEnum>;
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'rhythm'?: RitualDTORhythmEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualDTO
     */
    'preparationRequirements'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'semanticSummary'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'status'?: RitualDTOStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'createdBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'updatedAt'?: string;
}

export const RitualDTORitualTypesEnum = {
    Reflection: 'Reflection',
    Conversation: 'Conversation',
    Play: 'Play',
    Appreciation: 'Appreciation',
    Gratitude: 'Gratitude',
    PhysicalConnection: 'Physical Connection',
    QualityTime: 'Quality Time',
    Adventure: 'Adventure',
    Relaxation: 'Relaxation',
    SelfImprovement: 'Self-Improvement'
} as const;

export type RitualDTORitualTypesEnum = typeof RitualDTORitualTypesEnum[keyof typeof RitualDTORitualTypesEnum];
export const RitualDTORitualModeEnum = {
    Solo: 'SOLO',
    Partner: 'PARTNER',
    Pair: 'PAIR'
} as const;

export type RitualDTORitualModeEnum = typeof RitualDTORitualModeEnum[keyof typeof RitualDTORitualModeEnum];
export const RitualDTORitualTonesEnum = {
    Romantic: 'Romantic',
    Playful: 'Playful',
    Serious: 'Serious',
    Lighthearted: 'Lighthearted',
    Intimate: 'Intimate',
    Adventurous: 'Adventurous',
    Calm: 'Calm',
    Energetic: 'Energetic',
    Thoughtful: 'Thoughtful',
    Spontaneous: 'Spontaneous'
} as const;

export type RitualDTORitualTonesEnum = typeof RitualDTORitualTonesEnum[keyof typeof RitualDTORitualTonesEnum];
export const RitualDTOSensitivityLevelEnum = {
    Low: 'LOW',
    Moderate: 'MODERATE',
    High: 'HIGH'
} as const;

export type RitualDTOSensitivityLevelEnum = typeof RitualDTOSensitivityLevelEnum[keyof typeof RitualDTOSensitivityLevelEnum];
export const RitualDTOEffortLevelEnum = {
    Low: 'LOW',
    Moderate: 'MODERATE',
    High: 'HIGH'
} as const;

export type RitualDTOEffortLevelEnum = typeof RitualDTOEffortLevelEnum[keyof typeof RitualDTOEffortLevelEnum];
export const RitualDTOLoveTypesSupportedEnum = {
    Belong: 'BELONG',
    Fire: 'FIRE',
    Spark: 'SPARK',
    Care: 'CARE',
    Self: 'SELF',
    Build: 'BUILD',
    Grow: 'GROW',
    Beyond: 'BEYOND',
    Grace: 'GRACE'
} as const;

export type RitualDTOLoveTypesSupportedEnum = typeof RitualDTOLoveTypesSupportedEnum[keyof typeof RitualDTOLoveTypesSupportedEnum];
export const RitualDTOEmotionalStatesSupportedEnum = {
    Happy: 'Happy',
    Sad: 'Sad',
    Anxious: 'Anxious',
    Peaceful: 'Peaceful',
    Excited: 'Excited',
    Tired: 'Tired',
    Stressed: 'Stressed',
    Loving: 'Loving',
    Grateful: 'Grateful',
    Frustrated: 'Frustrated',
    Overwhelmed: 'Overwhelmed'
} as const;

export type RitualDTOEmotionalStatesSupportedEnum = typeof RitualDTOEmotionalStatesSupportedEnum[keyof typeof RitualDTOEmotionalStatesSupportedEnum];
export const RitualDTORelationalNeedsServedEnum = {
    Connection: 'Connection',
    Appreciation: 'Appreciation',
    Respect: 'Respect',
    Trust: 'Trust',
    Intimacy: 'Intimacy',
    Support: 'Support',
    Acceptance: 'Acceptance',
    Space: 'Space',
    Security: 'Security',
    Adventure: 'Adventure'
} as const;

export type RitualDTORelationalNeedsServedEnum = typeof RitualDTORelationalNeedsServedEnum[keyof typeof RitualDTORelationalNeedsServedEnum];
export const RitualDTOLifeContextsRelevantEnum = {
    MorningRoutine: 'Morning Routine',
    EveningRoutine: 'Evening Routine',
    Weekend: 'Weekend',
    Holiday: 'Holiday',
    Anniversary: 'Anniversary',
    DateNight: 'Date Night',
    LongDistance: 'Long Distance',
    StressfulPeriod: 'Stressful Period',
    NewRelationship: 'New Relationship',
    LongTermRelationship: 'Long-term Relationship'
} as const;

export type RitualDTOLifeContextsRelevantEnum = typeof RitualDTOLifeContextsRelevantEnum[keyof typeof RitualDTOLifeContextsRelevantEnum];
export const RitualDTORhythmEnum = {
    Daily: 'DAILY',
    Weekly: 'WEEKLY',
    Occasional: 'OCCASIONAL',
    EventTriggered: 'EVENT_TRIGGERED'
} as const;

export type RitualDTORhythmEnum = typeof RitualDTORhythmEnum[keyof typeof RitualDTORhythmEnum];
export const RitualDTOStatusEnum = {
    Published: 'PUBLISHED',
    Draft: 'DRAFT',
    Archived: 'ARCHIVED'
} as const;

export type RitualDTOStatusEnum = typeof RitualDTOStatusEnum[keyof typeof RitualDTOStatusEnum];


