/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RitualDTO } from './ritual-dto';

/**
 * 
 * @export
 * @interface RitualPackDTO
 */
export interface RitualPackDTO {
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'shortDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'fullDescription'?: string;
    /**
     * 
     * @type {Array<RitualDTO>}
     * @memberof RitualPackDTO
     */
    'rituals'?: Array<RitualDTO>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualPackDTO
     */
    'ritualTypes'?: Array<RitualTypesEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualPackDTO
     */
    'ritualTones'?: Array<RitualTonesEnum>;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'sensitivityLevel'?: SensitivityLevelEnum;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'effortLevel'?: EffortLevelEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualPackDTO
     */
    'loveTypesSupported'?: Array<LoveTypesSupportedEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualPackDTO
     */
    'emotionalStatesSupported'?: Array<EmotionalStatesSupportedEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualPackDTO
     */
    'relationalNeedsServed'?: Array<RelationalNeedsServedEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualPackDTO
     */
    'lifeContextsRelevant'?: Array<LifeContextsRelevantEnum>;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'semanticSummary'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'status'?: StatusEnum;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'createdBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualPackDTO
     */
    'updatedAt'?: string;
}

export const RitualTypesEnum = {
    Reflection: 'Reflection',
    Conversation: 'Conversation',
    Play: 'Play',
    Appreciation: 'Appreciation',
    Gratitude: 'Gratitude',
    PhysicalConnection: 'Physical Connection',
    QualityTime: 'Quality Time',
    Adventure: 'Adventure',
    Relaxation: 'Relaxation',
    SelfImprovement: 'Self-Improvement'
} as const;

export type RitualTypesEnum = typeof RitualTypesEnum[keyof typeof RitualTypesEnum];
export const RitualTonesEnum = {
    Romantic: 'Romantic',
    Playful: 'Playful',
    Serious: 'Serious',
    Lighthearted: 'Lighthearted',
    Intimate: 'Intimate',
    Adventurous: 'Adventurous',
    Calm: 'Calm',
    Energetic: 'Energetic',
    Thoughtful: 'Thoughtful',
    Spontaneous: 'Spontaneous'
} as const;

export type RitualTonesEnum = typeof RitualTonesEnum[keyof typeof RitualTonesEnum];
export const SensitivityLevelEnum = {
    Low: 'LOW',
    Moderate: 'MODERATE',
    High: 'HIGH'
} as const;

export type SensitivityLevelEnum = typeof SensitivityLevelEnum[keyof typeof SensitivityLevelEnum];
export const EffortLevelEnum = {
    Low: 'LOW',
    Moderate: 'MODERATE',
    High: 'HIGH'
} as const;

export type EffortLevelEnum = typeof EffortLevelEnum[keyof typeof EffortLevelEnum];
export const LoveTypesSupportedEnum = {
    Belong: 'BELONG',
    Fire: 'FIRE',
    Spark: 'SPARK',
    Care: 'CARE',
    Self: 'SELF',
    Build: 'BUILD',
    Grow: 'GROW',
    Beyond: 'BEYOND',
    Grace: 'GRACE'
} as const;

export type LoveTypesSupportedEnum = typeof LoveTypesSupportedEnum[keyof typeof LoveTypesSupportedEnum];
export const EmotionalStatesSupportedEnum = {
    Happy: 'Happy',
    Sad: 'Sad',
    Anxious: 'Anxious',
    Peaceful: 'Peaceful',
    Excited: 'Excited',
    Tired: 'Tired',
    Stressed: 'Stressed',
    Loving: 'Loving',
    Grateful: 'Grateful',
    Frustrated: 'Frustrated',
    Overwhelmed: 'Overwhelmed'
} as const;

export type EmotionalStatesSupportedEnum = typeof EmotionalStatesSupportedEnum[keyof typeof EmotionalStatesSupportedEnum];
export const RelationalNeedsServedEnum = {
    Connection: 'Connection',
    Appreciation: 'Appreciation',
    Respect: 'Respect',
    Trust: 'Trust',
    Intimacy: 'Intimacy',
    Support: 'Support',
    Acceptance: 'Acceptance',
    Space: 'Space',
    Security: 'Security',
    Adventure: 'Adventure'
} as const;

export type RelationalNeedsServedEnum = typeof RelationalNeedsServedEnum[keyof typeof RelationalNeedsServedEnum];
export const LifeContextsRelevantEnum = {
    MorningRoutine: 'Morning Routine',
    EveningRoutine: 'Evening Routine',
    Weekend: 'Weekend',
    Holiday: 'Holiday',
    Anniversary: 'Anniversary',
    DateNight: 'Date Night',
    LongDistance: 'Long Distance',
    StressfulPeriod: 'Stressful Period',
    NewRelationship: 'New Relationship',
    LongTermRelationship: 'Long-term Relationship'
} as const;

export type LifeContextsRelevantEnum = typeof LifeContextsRelevantEnum[keyof typeof LifeContextsRelevantEnum];
export const StatusEnum = {
    Published: 'PUBLISHED',
    Draft: 'DRAFT',
    Archived: 'ARCHIVED'
} as const;

export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];


