/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RitualHistoryDTO
 */
export interface RitualHistoryDTO {
    /**
     * 
     * @type {string}
     * @memberof RitualHistoryDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualHistoryDTO
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualHistoryDTO
     */
    'ritualId'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualHistoryDTO
     */
    'ritualPackId'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualHistoryDTO
     */
    'status'?: RitualHistoryDTOStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof RitualHistoryDTO
     */
    'feedback'?: RitualHistoryDTOFeedbackEnum;
    /**
     * 
     * @type {string}
     * @memberof RitualHistoryDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualHistoryDTO
     */
    'updatedAt'?: string;
}

export const RitualHistoryDTOStatusEnum = {
    Suggested: 'SUGGESTED',
    Active: 'ACTIVE',
    Started: 'STARTED',
    Completed: 'COMPLETED',
    Skipped: 'SKIPPED',
    Abandoned: 'ABANDONED'
} as const;

export type RitualHistoryDTOStatusEnum = typeof RitualHistoryDTOStatusEnum[keyof typeof RitualHistoryDTOStatusEnum];
export const RitualHistoryDTOFeedbackEnum = {
    Heart: 'HEART',
    Smile: 'SMILE',
    Neutral: 'NEUTRAL',
    Sad: 'SAD',
    Angry: 'ANGRY',
    Fire: 'FIRE',
    ThumbsUp: 'THUMBS_UP',
    ThumbsDown: 'THUMBS_DOWN'
} as const;

export type RitualHistoryDTOFeedbackEnum = typeof RitualHistoryDTOFeedbackEnum[keyof typeof RitualHistoryDTOFeedbackEnum];


