/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EffortLevel } from './effort-level';
// May contain unused imports in some cases
// @ts-ignore
import type { EmotionalState } from './emotional-state';
// May contain unused imports in some cases
// @ts-ignore
import type { LifeContext } from './life-context';
// May contain unused imports in some cases
// @ts-ignore
import type { LoveType } from './love-type';
// May contain unused imports in some cases
// @ts-ignore
import type { MediaAsset } from './media-asset';
// May contain unused imports in some cases
// @ts-ignore
import type { PublicationStatus } from './publication-status';
// May contain unused imports in some cases
// @ts-ignore
import type { RelationalNeed } from './relational-need';
// May contain unused imports in some cases
// @ts-ignore
import type { Rhythm } from './rhythm';
// May contain unused imports in some cases
// @ts-ignore
import type { RitualMode } from './ritual-mode';
// May contain unused imports in some cases
// @ts-ignore
import type { RitualStep } from './ritual-step';
// May contain unused imports in some cases
// @ts-ignore
import type { RitualTone } from './ritual-tone';
// May contain unused imports in some cases
// @ts-ignore
import type { RitualType } from './ritual-type';
// May contain unused imports in some cases
// @ts-ignore
import type { SensitivityLevel } from './sensitivity-level';

/**
 * 
 * @export
 * @interface RitualDTO
 */
export interface RitualDTO {
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'shortDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'fullDescription'?: string;
    /**
     * 
     * @type {Array<RitualType>}
     * @memberof RitualDTO
     */
    'ritualTypes'?: Array<RitualType>;
    /**
     * 
     * @type {RitualMode}
     * @memberof RitualDTO
     */
    'ritualMode'?: RitualMode;
    /**
     * 
     * @type {Array<RitualTone>}
     * @memberof RitualDTO
     */
    'ritualTones'?: Array<RitualTone>;
    /**
     * 
     * @type {SensitivityLevel}
     * @memberof RitualDTO
     */
    'sensitivityLevel'?: SensitivityLevel;
    /**
     * 
     * @type {EffortLevel}
     * @memberof RitualDTO
     */
    'effortLevel'?: EffortLevel;
    /**
     * 
     * @type {number}
     * @memberof RitualDTO
     */
    'estimatedDurationMinutes'?: number;
    /**
     * 
     * @type {Array<RitualStep>}
     * @memberof RitualDTO
     */
    'ritualSteps'?: Array<RitualStep>;
    /**
     * 
     * @type {Array<MediaAsset>}
     * @memberof RitualDTO
     */
    'mediaAssets'?: Array<MediaAsset>;
    /**
     * 
     * @type {Array<LoveType>}
     * @memberof RitualDTO
     */
    'loveTypesSupported'?: Array<LoveType>;
    /**
     * 
     * @type {Array<EmotionalState>}
     * @memberof RitualDTO
     */
    'emotionalStatesSupported'?: Array<EmotionalState>;
    /**
     * 
     * @type {Array<RelationalNeed>}
     * @memberof RitualDTO
     */
    'relationalNeedsServed'?: Array<RelationalNeed>;
    /**
     * 
     * @type {Array<LifeContext>}
     * @memberof RitualDTO
     */
    'lifeContextsRelevant'?: Array<LifeContext>;
    /**
     * 
     * @type {Rhythm}
     * @memberof RitualDTO
     */
    'rhythm'?: Rhythm;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualDTO
     */
    'preparationRequirements'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'semanticSummary'?: string;
    /**
     * 
     * @type {PublicationStatus}
     * @memberof RitualDTO
     */
    'status'?: PublicationStatus;
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'createdBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof RitualDTO
     */
    'updatedAt'?: string;
}



