/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RitualFilterRequest
 */
export interface RitualFilterRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualFilterRequest
     */
    'loveTypes'?: Array<RitualFilterRequestLoveTypesEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualFilterRequest
     */
    'ritualTypes'?: Array<RitualFilterRequestRitualTypesEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualFilterRequest
     */
    'ritualModes'?: Array<RitualFilterRequestRitualModesEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualFilterRequest
     */
    'emotionalStates'?: Array<RitualFilterRequestEmotionalStatesEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RitualFilterRequest
     */
    'relationalNeeds'?: Array<RitualFilterRequestRelationalNeedsEnum>;
}

export const RitualFilterRequestLoveTypesEnum = {
    Belong: 'BELONG',
    Fire: 'FIRE',
    Spark: 'SPARK',
    Care: 'CARE',
    Self: 'SELF',
    Build: 'BUILD',
    Grow: 'GROW',
    Beyond: 'BEYOND',
    Grace: 'GRACE'
} as const;

export type RitualFilterRequestLoveTypesEnum = typeof RitualFilterRequestLoveTypesEnum[keyof typeof RitualFilterRequestLoveTypesEnum];
export const RitualFilterRequestRitualTypesEnum = {
    Reflection: 'Reflection',
    Conversation: 'Conversation',
    Play: 'Play',
    Appreciation: 'Appreciation',
    Gratitude: 'Gratitude',
    PhysicalConnection: 'Physical Connection',
    QualityTime: 'Quality Time',
    Adventure: 'Adventure',
    Relaxation: 'Relaxation',
    SelfImprovement: 'Self-Improvement'
} as const;

export type RitualFilterRequestRitualTypesEnum = typeof RitualFilterRequestRitualTypesEnum[keyof typeof RitualFilterRequestRitualTypesEnum];
export const RitualFilterRequestRitualModesEnum = {
    Solo: 'SOLO',
    Partner: 'PARTNER',
    Pair: 'PAIR'
} as const;

export type RitualFilterRequestRitualModesEnum = typeof RitualFilterRequestRitualModesEnum[keyof typeof RitualFilterRequestRitualModesEnum];
export const RitualFilterRequestEmotionalStatesEnum = {
    Happy: 'Happy',
    Sad: 'Sad',
    Anxious: 'Anxious',
    Peaceful: 'Peaceful',
    Excited: 'Excited',
    Tired: 'Tired',
    Stressed: 'Stressed',
    Loving: 'Loving',
    Grateful: 'Grateful',
    Frustrated: 'Frustrated',
    Overwhelmed: 'Overwhelmed'
} as const;

export type RitualFilterRequestEmotionalStatesEnum = typeof RitualFilterRequestEmotionalStatesEnum[keyof typeof RitualFilterRequestEmotionalStatesEnum];
export const RitualFilterRequestRelationalNeedsEnum = {
    Connection: 'Connection',
    Appreciation: 'Appreciation',
    Respect: 'Respect',
    Trust: 'Trust',
    Intimacy: 'Intimacy',
    Support: 'Support',
    Acceptance: 'Acceptance',
    Space: 'Space',
    Security: 'Security',
    Adventure: 'Adventure'
} as const;

export type RitualFilterRequestRelationalNeedsEnum = typeof RitualFilterRequestRelationalNeedsEnum[keyof typeof RitualFilterRequestRelationalNeedsEnum];


