/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RitualHistoryStatusUpdateRequest
 */
export interface RitualHistoryStatusUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof RitualHistoryStatusUpdateRequest
     */
    'status'?: StatusEnum;
    /**
     * 
     * @type {string}
     * @memberof RitualHistoryStatusUpdateRequest
     */
    'feedback'?: FeedbackEnum;
}

export const StatusEnum = {
    Suggested: 'SUGGESTED',
    Active: 'ACTIVE',
    Started: 'STARTED',
    Completed: 'COMPLETED',
    Skipped: 'SKIPPED',
    Abandoned: 'ABANDONED'
} as const;

export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
export const FeedbackEnum = {
    Heart: 'HEART',
    Smile: 'SMILE',
    Neutral: 'NEUTRAL',
    Sad: 'SAD',
    Angry: 'ANGRY',
    Fire: 'FIRE',
    ThumbsUp: 'THUMBS_UP',
    ThumbsDown: 'THUMBS_DOWN'
} as const;

export type FeedbackEnum = typeof FeedbackEnum[keyof typeof FeedbackEnum];


