/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RitualDTO } from './ritual-dto';

/**
 * 
 * @export
 * @interface RitualInPackDTO
 */
export interface RitualInPackDTO {
    /**
     * 
     * @type {RitualDTO}
     * @memberof RitualInPackDTO
     */
    'ritual': RitualDTO;
    /**
     * 
     * @type {number}
     * @memberof RitualInPackDTO
     */
    'position': number;
}

