/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TagValueDTO } from './tag-value-dto';

/**
 * 
 * @export
 * @interface RitualTagDTO
 */
export interface RitualTagDTO {
    /**
     * 
     * @type {string}
     * @memberof RitualTagDTO
     */
    'displayName'?: string;
    /**
     * 
     * @type {number}
     * @memberof RitualTagDTO
     */
    'position'?: number;
    /**
     * 
     * @type {Array<TagValueDTO>}
     * @memberof RitualTagDTO
     */
    'values'?: Array<TagValueDTO>;
}

