/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const RitualHistoryStatus = {
    Suggested: 'SUGGESTED',
    Active: 'ACTIVE',
    Started: 'STARTED',
    Completed: 'COMPLETED',
    Skipped: 'SKIPPED',
    Abandoned: 'ABANDONED'
} as const;

export type RitualHistoryStatus = typeof RitualHistoryStatus[keyof typeof RitualHistoryStatus];



