/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LoveType } from './love-type';
// May contain unused imports in some cases
// @ts-ignore
import type { PublicationStatus } from './publication-status';
// May contain unused imports in some cases
// @ts-ignore
import type { RelationalNeed } from './relational-need';
// May contain unused imports in some cases
// @ts-ignore
import type { RitualMode } from './ritual-mode';
// May contain unused imports in some cases
// @ts-ignore
import type { RitualTone } from './ritual-tone';
// May contain unused imports in some cases
// @ts-ignore
import type { TimeTaken } from './time-taken';

/**
 * 
 * @export
 * @interface RitualFilterDTO
 */
export interface RitualFilterDTO {
    /**
     * 
     * @type {Array<LoveType>}
     * @memberof RitualFilterDTO
     */
    'loveTypes'?: Array<LoveType>;
    /**
     * 
     * @type {Array<RitualMode>}
     * @memberof RitualFilterDTO
     */
    'ritualModes'?: Array<RitualMode>;
    /**
     * 
     * @type {Array<TimeTaken>}
     * @memberof RitualFilterDTO
     */
    'timeTaken'?: Array<TimeTaken>;
    /**
     * 
     * @type {Array<RelationalNeed>}
     * @memberof RitualFilterDTO
     */
    'relationalNeeds'?: Array<RelationalNeed>;
    /**
     * 
     * @type {Array<RitualTone>}
     * @memberof RitualFilterDTO
     */
    'ritualTones'?: Array<RitualTone>;
    /**
     * 
     * @type {PublicationStatus}
     * @memberof RitualFilterDTO
     */
    'status'?: PublicationStatus;
}



