/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EmotionalState } from './emotional-state';
// May contain unused imports in some cases
// @ts-ignore
import type { LoveType } from './love-type';
// May contain unused imports in some cases
// @ts-ignore
import type { RelationalNeed } from './relational-need';
// May contain unused imports in some cases
// @ts-ignore
import type { RitualMode } from './ritual-mode';
// May contain unused imports in some cases
// @ts-ignore
import type { RitualType } from './ritual-type';

/**
 * 
 * @export
 * @interface RitualFilterRequest
 */
export interface RitualFilterRequest {
    /**
     * 
     * @type {Array<LoveType>}
     * @memberof RitualFilterRequest
     */
    'loveTypes'?: Array<LoveType>;
    /**
     * 
     * @type {Array<RitualType>}
     * @memberof RitualFilterRequest
     */
    'ritualTypes'?: Array<RitualType>;
    /**
     * 
     * @type {Array<RitualMode>}
     * @memberof RitualFilterRequest
     */
    'ritualModes'?: Array<RitualMode>;
    /**
     * 
     * @type {Array<EmotionalState>}
     * @memberof RitualFilterRequest
     */
    'emotionalStates'?: Array<EmotionalState>;
    /**
     * 
     * @type {Array<RelationalNeed>}
     * @memberof RitualFilterRequest
     */
    'relationalNeeds'?: Array<RelationalNeed>;
}

