/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RitualTagDTO } from './ritual-tag-dto';

/**
 * 
 * @export
 * @interface RitualTagsDTO
 */
export interface RitualTagsDTO {
    /**
     * 
     * @type {RitualTagDTO}
     * @memberof RitualTagsDTO
     */
    'loveTypes'?: RitualTagDTO;
    /**
     * 
     * @type {RitualTagDTO}
     * @memberof RitualTagsDTO
     */
    'ritualTypes'?: RitualTagDTO;
    /**
     * 
     * @type {RitualTagDTO}
     * @memberof RitualTagsDTO
     */
    'ritualModes'?: RitualTagDTO;
    /**
     * 
     * @type {RitualTagDTO}
     * @memberof RitualTagsDTO
     */
    'emotionalStates'?: RitualTagDTO;
    /**
     * 
     * @type {RitualTagDTO}
     * @memberof RitualTagsDTO
     */
    'relationalNeeds'?: RitualTagDTO;
}

