/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SubscriptionStatus } from './subscription-status';
// May contain unused imports in some cases
// @ts-ignore
import type { SubscriptionTier } from './subscription-tier';

/**
 * 
 * @export
 * @interface SubscriptionDTO
 */
export interface SubscriptionDTO {
    /**
     * 
     * @type {SubscriptionTier}
     * @memberof SubscriptionDTO
     */
    'tier': SubscriptionTier;
    /**
     * 
     * @type {SubscriptionStatus}
     * @memberof SubscriptionDTO
     */
    'status': SubscriptionStatus;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionDTO
     */
    'expiresAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionDTO
     */
    'isBetaUser': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionDTO
     */
    'hasPremiumAccess': boolean;
}



