/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const TimeContext = {
    Morning: 'MORNING',
    Afternoon: 'AFTERNOON',
    Evening: 'EVENING',
    Night: 'NIGHT',
    Weekday: 'WEEKDAY',
    Weekend: 'WEEKEND',
    Holiday: 'HOLIDAY',
    Anytime: 'ANYTIME'
} as const;

export type TimeContext = typeof TimeContext[keyof typeof TimeContext];



