/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const TimeTaken = {
    Moment: 'MOMENT',
    Short: 'SHORT',
    Medium: 'MEDIUM',
    Long: 'LONG',
    Extended: 'EXTENDED',
    Flexible: 'FLEXIBLE'
} as const;

export type TimeTaken = typeof TimeTaken[keyof typeof TimeTaken];



