/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Journey } from './journey';
// May contain unused imports in some cases
// @ts-ignore
import type { LoveType } from './love-type';
// May contain unused imports in some cases
// @ts-ignore
import type { RelationalNeed } from './relational-need';
// May contain unused imports in some cases
// @ts-ignore
import type { RelationshipStatus } from './relationship-status';

/**
 * 
 * @export
 * @interface UserContextDTO
 */
export interface UserContextDTO {
    /**
     * 
     * @type {string}
     * @memberof UserContextDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserContextDTO
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserContextDTO
     */
    'conversationId'?: string;
    /**
     * 
     * @type {Journey}
     * @memberof UserContextDTO
     */
    'journey'?: Journey;
    /**
     * 
     * @type {Array<LoveType>}
     * @memberof UserContextDTO
     */
    'loveTypes'?: Array<LoveType>;
    /**
     * 
     * @type {Array<RelationalNeed>}
     * @memberof UserContextDTO
     */
    'relationalNeeds'?: Array<RelationalNeed>;
    /**
     * 
     * @type {RelationshipStatus}
     * @memberof UserContextDTO
     */
    'relationshipStatus'?: RelationshipStatus;
    /**
     * 
     * @type {string}
     * @memberof UserContextDTO
     */
    'semanticSummary'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserContextDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserContextDTO
     */
    'updatedAt'?: string;
}



