/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserContextDTO
 */
export interface UserContextDTO {
    /**
     * 
     * @type {string}
     * @memberof UserContextDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserContextDTO
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserContextDTO
     */
    'conversationId'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserContextDTO
     */
    'emotionalStates'?: Array<EmotionalStatesEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserContextDTO
     */
    'relationalNeeds'?: Array<RelationalNeedsEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserContextDTO
     */
    'preferredLoveLanguages'?: Array<PreferredLoveLanguagesEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserContextDTO
     */
    'preferredRitualTypes'?: Array<PreferredRitualTypesEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserContextDTO
     */
    'preferredTones'?: Array<PreferredTonesEnum>;
    /**
     * 
     * @type {number}
     * @memberof UserContextDTO
     */
    'availableTimeMinutes'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserContextDTO
     */
    'preferredEffortLevel'?: PreferredEffortLevelEnum;
    /**
     * 
     * @type {string}
     * @memberof UserContextDTO
     */
    'preferredIntensity'?: PreferredIntensityEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserContextDTO
     */
    'currentContexts'?: Array<CurrentContextsEnum>;
    /**
     * 
     * @type {string}
     * @memberof UserContextDTO
     */
    'timeContext'?: TimeContextEnum;
    /**
     * 
     * @type {string}
     * @memberof UserContextDTO
     */
    'relationshipStatus'?: RelationshipStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UserContextDTO
     */
    'semanticQuery'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserContextDTO
     */
    'lastInteractionAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserContextDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserContextDTO
     */
    'updatedAt'?: string;
}

export const EmotionalStatesEnum = {
    Happy: 'Happy',
    Sad: 'Sad',
    Anxious: 'Anxious',
    Peaceful: 'Peaceful',
    Excited: 'Excited',
    Tired: 'Tired',
    Stressed: 'Stressed',
    Loving: 'Loving',
    Grateful: 'Grateful',
    Frustrated: 'Frustrated',
    Overwhelmed: 'Overwhelmed'
} as const;

export type EmotionalStatesEnum = typeof EmotionalStatesEnum[keyof typeof EmotionalStatesEnum];
export const RelationalNeedsEnum = {
    Connection: 'Connection',
    Appreciation: 'Appreciation',
    Respect: 'Respect',
    Trust: 'Trust',
    Intimacy: 'Intimacy',
    Support: 'Support',
    Acceptance: 'Acceptance',
    Space: 'Space',
    Security: 'Security',
    Adventure: 'Adventure'
} as const;

export type RelationalNeedsEnum = typeof RelationalNeedsEnum[keyof typeof RelationalNeedsEnum];
export const PreferredLoveLanguagesEnum = {
    Belong: 'BELONG',
    Fire: 'FIRE',
    Spark: 'SPARK',
    Care: 'CARE',
    Self: 'SELF',
    Build: 'BUILD',
    Grow: 'GROW',
    Beyond: 'BEYOND',
    Grace: 'GRACE'
} as const;

export type PreferredLoveLanguagesEnum = typeof PreferredLoveLanguagesEnum[keyof typeof PreferredLoveLanguagesEnum];
export const PreferredRitualTypesEnum = {
    Reflection: 'Reflection',
    Conversation: 'Conversation',
    Play: 'Play',
    Appreciation: 'Appreciation',
    Gratitude: 'Gratitude',
    PhysicalConnection: 'Physical Connection',
    QualityTime: 'Quality Time',
    Adventure: 'Adventure',
    Relaxation: 'Relaxation',
    SelfImprovement: 'Self-Improvement'
} as const;

export type PreferredRitualTypesEnum = typeof PreferredRitualTypesEnum[keyof typeof PreferredRitualTypesEnum];
export const PreferredTonesEnum = {
    Romantic: 'Romantic',
    Playful: 'Playful',
    Serious: 'Serious',
    Lighthearted: 'Lighthearted',
    Intimate: 'Intimate',
    Adventurous: 'Adventurous',
    Calm: 'Calm',
    Energetic: 'Energetic',
    Thoughtful: 'Thoughtful',
    Spontaneous: 'Spontaneous'
} as const;

export type PreferredTonesEnum = typeof PreferredTonesEnum[keyof typeof PreferredTonesEnum];
export const PreferredEffortLevelEnum = {
    Low: 'LOW',
    Moderate: 'MODERATE',
    High: 'HIGH'
} as const;

export type PreferredEffortLevelEnum = typeof PreferredEffortLevelEnum[keyof typeof PreferredEffortLevelEnum];
export const PreferredIntensityEnum = {
    Low: 'LOW',
    Moderate: 'MODERATE',
    High: 'HIGH',
    Intense: 'INTENSE'
} as const;

export type PreferredIntensityEnum = typeof PreferredIntensityEnum[keyof typeof PreferredIntensityEnum];
export const CurrentContextsEnum = {
    MorningRoutine: 'Morning Routine',
    EveningRoutine: 'Evening Routine',
    Weekend: 'Weekend',
    Holiday: 'Holiday',
    Anniversary: 'Anniversary',
    DateNight: 'Date Night',
    LongDistance: 'Long Distance',
    StressfulPeriod: 'Stressful Period',
    NewRelationship: 'New Relationship',
    LongTermRelationship: 'Long-term Relationship'
} as const;

export type CurrentContextsEnum = typeof CurrentContextsEnum[keyof typeof CurrentContextsEnum];
export const TimeContextEnum = {
    Morning: 'MORNING',
    Afternoon: 'AFTERNOON',
    Evening: 'EVENING',
    Night: 'NIGHT',
    Weekday: 'WEEKDAY',
    Weekend: 'WEEKEND',
    Holiday: 'HOLIDAY',
    Anytime: 'ANYTIME'
} as const;

export type TimeContextEnum = typeof TimeContextEnum[keyof typeof TimeContextEnum];
export const RelationshipStatusEnum = {
    New: 'NEW',
    Established: 'ESTABLISHED',
    Committed: 'COMMITTED',
    Engaged: 'ENGAGED',
    Married: 'MARRIED',
    Rekindling: 'REKINDLING',
    LongDistance: 'LONG_DISTANCE',
    Casual: 'CASUAL',
    Exploring: 'EXPLORING',
    Other: 'OTHER'
} as const;

export type RelationshipStatusEnum = typeof RelationshipStatusEnum[keyof typeof RelationshipStatusEnum];


