/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RitualPackDTO } from './ritual-pack-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { UserRitualDTO } from './user-ritual-dto';

/**
 * 
 * @export
 * @interface UserRitualPackDTO
 */
export interface UserRitualPackDTO {
    /**
     * 
     * @type {string}
     * @memberof UserRitualPackDTO
     */
    'ritualPackId': string;
    /**
     * 
     * @type {string}
     * @memberof UserRitualPackDTO
     */
    'recommendationId': string;
    /**
     * 
     * @type {RitualPackDTO}
     * @memberof UserRitualPackDTO
     */
    'ritualPack': RitualPackDTO;
    /**
     * 
     * @type {Array<UserRitualDTO>}
     * @memberof UserRitualPackDTO
     */
    'rituals': Array<UserRitualDTO>;
}

