/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserDTO
 */
export interface UserDTO {
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    'authUserId': string;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    'displayName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserDTO
     */
    'onboardingCompleted'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    'lastLoginAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    'updatedAt'?: string;
}

