/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UsagePeriodType } from './usage-period-type';

/**
 * 
 * @export
 * @interface UserUsageCounterDTO
 */
export interface UserUsageCounterDTO {
    /**
     * 
     * @type {string}
     * @memberof UserUsageCounterDTO
     */
    'id': string;
    /**
     * 
     * @type {UsagePeriodType}
     * @memberof UserUsageCounterDTO
     */
    'periodType': UsagePeriodType;
    /**
     * 
     * @type {string}
     * @memberof UserUsageCounterDTO
     */
    'periodStart': string;
    /**
     * 
     * @type {number}
     * @memberof UserUsageCounterDTO
     */
    'aiMessagesCount': number;
    /**
     * 
     * @type {number}
     * @memberof UserUsageCounterDTO
     */
    'recommendationsCount': number;
    /**
     * 
     * @type {string}
     * @memberof UserUsageCounterDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUsageCounterDTO
     */
    'updatedAt'?: string;
}



